# -*- coding: utf-8 -*-
"""superstore_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EorEEjvyPWMem2dfQsQOVJNKxmS5GsNa
"""

import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv("/content/Sample - Superstore.csv", encoding='latin1')

#Convert data columns
df['Order Date'] = pd.to_datetime(df['Order Date'])
df['Ship Date'] = pd.to_datetime(df['Ship Date'])

#Create Month and Year
df['Month'] = df['Order Date'].dt.month
df['Year'] = df['Order Date'].dt.year

#Total Sales by Category
sales_by_category = df.groupby('Category')['Sales'].sum()

#Profit by Sub-Category
profit_by_subcat = df.groupby('Sub-Category')['Profit'].sum().sort_values()

#Monthly Sales Trend
monthly_sales = df.groupby(df['Order Date'].dt.to_period('M'))['Sales'].sum()

#Average Discount by Segment
avg_discount_segment = df.groupby('Segment')['Discount'].mean()

#Visualizations
plt.figure(figsize=(16, 10))

#Sales by Category
plt.subplot(2, 2, 1)
sales_by_category.plot(kind='bar', color='skyblue')
plt.title('Total Sales by Category')
plt.ylabel('Sales ($)')

#Profit by Sub-Category
plt.subplot(2, 2, 2)
profit_by_subcat.plot(kind='barh', color='salmon')
plt.title('Profit by Sub-Category')
plt.xlabel('Profit ($)')

#Monthly Sales
plt.subplot(2, 2, 3)
monthly_sales.plot(marker='o')
plt.title('Monthly Sales Trend')
plt.ylabel('Sales ($)')
plt.xlabel('Month')

#Avg Discount by Segment
plt.subplot(2, 2, 4)
avg_discount_segment.plot(kind='bar', color='lightgreen')
plt.title('Average Discount by Segment')
plt.ylabel('Discount')

plt.tight_layout()
plt.show()